# Windows-only workflow for building and testing the SetsLibrary project

name: .NET Windows Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore "./Sets Library/Sets Library/Sets Library.csproj"

    - name: Build Solution
      run: dotnet build "./Sets Library/Sets Library/Sets Library.csproj" --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test "./Sets Library/SetsLibrary.Tests/SetsLibrary.Tests.csproj" --no-build --verbosity normal
